# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89637816dc7ea4049ff7f41d04536a9c23b0094450dec18f23b7e2bfc03c2e36c7c5f83f0306321f254f1047f9a2caffc989dd770ffc1acbbd9d2def5fbcfb9f

test:
  secret_key_base: dc1b0ca6f696d410361f2a7e343ed05299cca3d30dbe2204e98dc0637ff83c5f12fc3424678fe02eb0b63124514cbad00aac0e0c900bb3fdef1625b99c58bcd3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
